### PR TITLE
FEATURES: Cards Blade components

### PR DESCRIPTION
**Pull request by asantibanez**
## Summary

This PR adds custom Blade for the following Card examples:
- SimpleLink
- SimpleWithActions
- LinkWithMedia
- LinkWithMediaAndActions
- Event

## Stories

- https://www.notion.so/nuws/9686730340ce40758017f8c4f7009a68?v=f0ea964fd55b400db6848ab41528922a&p=a8216fe8ef684e89ad65d42cd91d1636

## Usage

SimpleLink

image

SimpleWithActions

image

LinkWithMedia

image

LinkWithMediaAndActions

image

Event

image

## Type of Change

- [x] :rocket: New Features

### CODE REVIEW

**Comment by asantibanez** [comment]
@jasonlbeggs 

I've just completed 2 of the 4 card components. Would like your feedback on the api to continue developing the other 2 that resemble pretty much these base ones.

Thanks!

**Comment by jasonlbeggs** [comment]
I like it so far! Let's also give the option to pass a slot for the main content (title and body), and maybe another slot for footer content in case they want something a little more custom. What do you think?

**Comment by asantibanez** [comment]
Hey @jasonlbeggs 

I've added slots named `main`, `actions` and `footer` that can be used to override the content 💪

**Comment by asantibanez** [comment]
@jasonlbeggs 

Ready for your review. Just missing the README update.

**Comment by jasonlbeggs** [comment]
@asantibanez this is looking good so far! Let me know when you've had a chance to update the README.

**Comment by asantibanez** [comment]
Hey @jasonlbeggs 

README almost ready. Event card was added too. Will have this one wrapped up in a few.

**Comment by asantibanez** [comment]
Ready @jasonlbeggs

**Comment by jasonlbeggs** [comment]
This is looking great! The only things I think would be good to do is remove all the widths and max-widths from the cards so users can handle that outside the cards and note that the @tailwindcss/aspect-ratio plugin is needed for the cards with media. Maybe link to the plugins page on the kernl-ui docs site so they know how to install that. Thanks man!

**Comment by asantibanez** [comment]
Sounds good @jasonlbeggs . Will add those shortly.

**Comment by asantibanez** [comment]
@jasonlbeggs 

I removed default sizing. However, cards that have an image use `max-w-` for the media itself. Because of that, the parent has to have the same `max-w-` class to match.

Removing it from the parent blows up.

Take a look at the event card

image

What should we do for this cases?

**Comment by jasonlbeggs** [comment]
Does adding w-full on the image container help?

**Comment by asantibanez** [comment]
@jasonlbeggs 

That did the trick. 😬

image

**Comment by asantibanez** [comment]
@jasonlbeggs 

Ready for re-review.

I left some of the `max-w-` classes, specially for `horizontal` and `horizontal-flipped` versions. These ones need the constrain in order to work properly.

Let me know what you think.

**Comment by jasonlbeggs** [comment]
These are looking great! Thanks!

**Pull request merged**
